import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";
import Provider from "@/components/Provider";
import { Toaster } from "@/components/ui/toaster";
import QueryProvider from "@/components/QuerryProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <QueryProvider>
        <div className="max-w-7xl  mx-auto">
          <div className="flex flex-col gap-3 p-2">
            <Navbar />
            <div>
            {children}
            <Toaster />
            </div>
          </div>
          </div>
          </QueryProvider>
          </Provider>
          </body>
    </html>
  );
}
